// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Delivery
{


    public partial class EmptyMasterPage
    {

        protected System.Web.UI.WebControls.Content GuestConten;

        protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
