// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Delivery
{


    public partial class Register
    {
        protected System.Web.UI.WebControls.Content MainContentContent;

        protected System.Web.UI.WebControls.TextBox tbUserLogin;

        protected System.Web.UI.WebControls.TextBox tbUserEmail;

        protected System.Web.UI.WebControls.TextBox tbUserFirstName;

        protected System.Web.UI.WebControls.TextBox tbUserLastName;

        protected System.Web.UI.WebControls.TextBox tbUserPhone;

        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        protected System.Web.UI.WebControls.TextBox tbUserPass;

        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;

        protected System.Web.UI.WebControls.CheckBox cbRememberMe;

        protected System.Web.UI.WebControls.Button bSubmit;

        protected System.Web.UI.WebControls.Label Msg;
    }
}
