//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverySite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PagesTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagesTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeliverySite.Resources.PagesTitles", typeof(PagesTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить анонимное сообщение.
        /// </summary>
        public static string ManagerAnonymousMessage {
            get {
                return ResourceManager.GetString("ManagerAnonymousMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог запросов к API.
        /// </summary>
        public static string ManagerApiLogsView {
            get {
                return ResourceManager.GetString("ManagerApiLogsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение конфигураций.
        /// </summary>
        public static string ManagerBackendEdit {
            get {
                return ResourceManager.GetString("ManagerBackendEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурации.
        /// </summary>
        public static string ManagerBackendView {
            get {
                return ResourceManager.GetString("ManagerBackendView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет.
        /// </summary>
        public static string ManagerCalculationView {
            get {
                return ResourceManager.GetString("ManagerCalculationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание автомобиля.
        /// </summary>
        public static string ManagerCarCreate {
            get {
                return ResourceManager.GetString("ManagerCarCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование автомобиля.
        /// </summary>
        public static string ManagerCarEdit {
            get {
                return ResourceManager.GetString("ManagerCarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобили.
        /// </summary>
        public static string ManagerCarsView {
            get {
                return ResourceManager.GetString("ManagerCarsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр автомобиля.
        /// </summary>
        public static string ManagerCarView {
            get {
                return ResourceManager.GetString("ManagerCarView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание категории.
        /// </summary>
        public static string ManagerCategoryCreateTitle {
            get {
                return ResourceManager.GetString("ManagerCategoryCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование категории.
        /// </summary>
        public static string ManagerCategoryEditTitle {
            get {
                return ResourceManager.GetString("ManagerCategoryEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string ManagerCategoryViewTitle {
            get {
                return ResourceManager.GetString("ManagerCategoryViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение паролей пользователей.
        /// </summary>
        public static string ManagerChangePassword {
            get {
                return ResourceManager.GetString("ManagerChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нас. пункта.
        /// </summary>
        public static string ManagerCityCreate {
            get {
                return ResourceManager.GetString("ManagerCityCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование нас. пункта.
        /// </summary>
        public static string ManagerCityEdit {
            get {
                return ResourceManager.GetString("ManagerCityEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список нас. пунктов.
        /// </summary>
        public static string ManagerCityView {
            get {
                return ResourceManager.GetString("ManagerCityView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание клиента.
        /// </summary>
        public static string ManagerClientCreateTitle {
            get {
                return ResourceManager.GetString("ManagerClientCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование клиента.
        /// </summary>
        public static string ManagerClientEditTitle {
            get {
                return ResourceManager.GetString("ManagerClientEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиенты.
        /// </summary>
        public static string ManagerClientViewTitle {
            get {
                return ResourceManager.GetString("ManagerClientViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кабинет сотрудника.
        /// </summary>
        public static string ManagerDefaultTitle {
            get {
                return ResourceManager.GetString("ManagerDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование района.
        /// </summary>
        public static string ManagerDistrictEdit {
            get {
                return ResourceManager.GetString("ManagerDistrictEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Районы.
        /// </summary>
        public static string ManagerDistrictsView {
            get {
                return ResourceManager.GetString("ManagerDistrictsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление водителя.
        /// </summary>
        public static string ManagerDriversCreate {
            get {
                return ResourceManager.GetString("ManagerDriversCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование водиля.
        /// </summary>
        public static string ManagerDriversEdit {
            get {
                return ResourceManager.GetString("ManagerDriversEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список водителей.
        /// </summary>
        public static string ManagerDriversView {
            get {
                return ResourceManager.GetString("ManagerDriversView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водитель.
        /// </summary>
        public static string ManagerDriverViewTitle {
            get {
                return ResourceManager.GetString("ManagerDriverViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование электронного сообщения.
        /// </summary>
        public static string ManagerEmailNotificationEdit {
            get {
                return ResourceManager.GetString("ManagerEmailNotificationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список электронных сообщений.
        /// </summary>
        public static string ManagerEmailNotificationView {
            get {
                return ResourceManager.GetString("ManagerEmailNotificationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр ошибки.
        /// </summary>
        public static string ManagerErrorsLogEdit {
            get {
                return ResourceManager.GetString("ManagerErrorsLogEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог системных ошибок.
        /// </summary>
        public static string ManagerErrorsLogView {
            get {
                return ResourceManager.GetString("ManagerErrorsLogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание рассчетного листа.
        /// </summary>
        public static string ManagerIssuanceListsCreateTitle {
            get {
                return ResourceManager.GetString("ManagerIssuanceListsCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование рассчетного листа #{0}.
        /// </summary>
        public static string ManagerIssuanceListsEditTitle {
            get {
                return ResourceManager.GetString("ManagerIssuanceListsEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчетные листы.
        /// </summary>
        public static string ManagerIssuanceListsViewTitle {
            get {
                return ResourceManager.GetString("ManagerIssuanceListsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчетный лист #{0}.
        /// </summary>
        public static string ManagerIssuanceListViewTitle {
            get {
                return ResourceManager.GetString("ManagerIssuanceListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки к выдаче.
        /// </summary>
        public static string ManagerIssuanceViewTitle {
            get {
                return ResourceManager.GetString("ManagerIssuanceViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог действий пользователей.
        /// </summary>
        public static string ManagerLogsView {
            get {
                return ResourceManager.GetString("ManagerLogsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание сотрудника.
        /// </summary>
        public static string ManagerManagerCreate {
            get {
                return ResourceManager.GetString("ManagerManagerCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование сотрудника.
        /// </summary>
        public static string ManagerManagerEdit {
            get {
                return ResourceManager.GetString("ManagerManagerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список сотрудников.
        /// </summary>
        public static string ManagerManagersView {
            get {
                return ResourceManager.GetString("ManagerManagersView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр сотрудника.
        /// </summary>
        public static string ManagerManagerView {
            get {
                return ResourceManager.GetString("ManagerManagerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заявок &quot;СТАТУС&quot;.
        /// </summary>
        public static string ManagerMoneyDeliveredView {
            get {
                return ResourceManager.GetString("ManagerMoneyDeliveredView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма за &quot;За услугу&quot;.
        /// </summary>
        public static string ManagerMoneyDeliveryView {
            get {
                return ResourceManager.GetString("ManagerMoneyDeliveryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроль водителя.
        /// </summary>
        public static string ManagerMoneyDriverViewTitle {
            get {
                return ResourceManager.GetString("ManagerMoneyDriverViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приемка.
        /// </summary>
        public static string ManagerMoneyViewTitle {
            get {
                return ResourceManager.GetString("ManagerMoneyViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчетный лист.
        /// </summary>
        public static string ManagerNewIssuanceViewTitle {
            get {
                return ResourceManager.GetString("ManagerNewIssuanceViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание новости.
        /// </summary>
        public static string ManagerNewsCreate {
            get {
                return ResourceManager.GetString("ManagerNewsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редатирование новости.
        /// </summary>
        public static string ManagerNewsEdit {
            get {
                return ResourceManager.GetString("ManagerNewsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лента новостей.
        /// </summary>
        public static string ManagerNewsFeedView {
            get {
                return ResourceManager.GetString("ManagerNewsFeedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр новости.
        /// </summary>
        public static string ManagerNewsFromFeedView {
            get {
                return ResourceManager.GetString("ManagerNewsFromFeedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список новостей.
        /// </summary>
        public static string ManagerNewsView {
            get {
                return ResourceManager.GetString("ManagerNewsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование уведомления или ошибоки.
        /// </summary>
        public static string ManagerNotificationEdit {
            get {
                return ResourceManager.GetString("ManagerNotificationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список уведомлений и ошибок сайта.
        /// </summary>
        public static string ManagerNotificationView {
            get {
                return ResourceManager.GetString("ManagerNotificationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование страницы.
        /// </summary>
        public static string ManagerPagesEdit {
            get {
                return ResourceManager.GetString("ManagerPagesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список страниц с контентом.
        /// </summary>
        public static string ManagerPagesView {
            get {
                return ResourceManager.GetString("ManagerPagesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование профиля.
        /// </summary>
        public static string ManagerProfileEditTitle {
            get {
                return ResourceManager.GetString("ManagerProfileEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        public static string ManagerProfilesViewTitle {
            get {
                return ResourceManager.GetString("ManagerProfilesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание поставщика.
        /// </summary>
        public static string ManagerProviderCreate {
            get {
                return ResourceManager.GetString("ManagerProviderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование поставщика.
        /// </summary>
        public static string ManagerProviderEdit {
            get {
                return ResourceManager.GetString("ManagerProviderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База поставщиков.
        /// </summary>
        public static string ManagerProvidersView {
            get {
                return ResourceManager.GetString("ManagerProvidersView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование документов.
        /// </summary>
        public static string ManagerReportsEditTitle {
            get {
                return ResourceManager.GetString("ManagerReportsEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт данных.
        /// </summary>
        public static string ManagerReportsExportTitle {
            get {
                return ResourceManager.GetString("ManagerReportsExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив документов.
        /// </summary>
        public static string ManagerReportsViewTitle {
            get {
                return ResourceManager.GetString("ManagerReportsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание роли.
        /// </summary>
        public static string ManagerRolesCreate {
            get {
                return ResourceManager.GetString("ManagerRolesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование роли.
        /// </summary>
        public static string ManagerRolesEdit {
            get {
                return ResourceManager.GetString("ManagerRolesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список ролей.
        /// </summary>
        public static string ManagerRolesView {
            get {
                return ResourceManager.GetString("ManagerRolesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка КП.
        /// </summary>
        public static string ManagerSendComProp {
            get {
                return ResourceManager.GetString("ManagerSendComProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание наименования.
        /// </summary>
        public static string ManagerTitlesCreateTitle {
            get {
                return ResourceManager.GetString("ManagerTitlesCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование наименования.
        /// </summary>
        public static string ManagerTitlesEditTitle {
            get {
                return ResourceManager.GetString("ManagerTitlesEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименования.
        /// </summary>
        public static string ManagerTitlesViewTitle {
            get {
                return ResourceManager.GetString("ManagerTitlesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление направления.
        /// </summary>
        public static string ManagerTracksCreate {
            get {
                return ResourceManager.GetString("ManagerTracksCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование направления.
        /// </summary>
        public static string ManagerTracksEdit {
            get {
                return ResourceManager.GetString("ManagerTracksEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список направлений.
        /// </summary>
        public static string ManagerTracksView {
            get {
                return ResourceManager.GetString("ManagerTracksView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидки клиентов.
        /// </summary>
        public static string ManagerUsersDiscount {
            get {
                return ResourceManager.GetString("ManagerUsersDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Едут завтра.
        /// </summary>
        public static string ManagerUserTicketByDeliveryDateView {
            get {
                return ResourceManager.GetString("ManagerUserTicketByDeliveryDateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Едут послезавтра и далее.
        /// </summary>
        public static string ManagerUserTicketByDeliveryDateViewTwo {
            get {
                return ResourceManager.GetString("ManagerUserTicketByDeliveryDateViewTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки Минск.
        /// </summary>
        public static string ManagerUserTicketByDeliveryOnMinsk {
            get {
                return ResourceManager.GetString("ManagerUserTicketByDeliveryOnMinsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование заявки.
        /// </summary>
        public static string ManagerUserTicketEditTitle {
            get {
                return ResourceManager.GetString("ManagerUserTicketEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необработанные заявки.
        /// </summary>
        public static string ManagerUserTicketNotProcessedView {
            get {
                return ResourceManager.GetString("ManagerUserTicketNotProcessedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки моих клиентов.
        /// </summary>
        public static string ManagerUserTicketViewMyTitle {
            get {
                return ResourceManager.GetString("ManagerUserTicketViewMyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки.
        /// </summary>
        public static string ManagerUserTicketViewTitle {
            get {
                return ResourceManager.GetString("ManagerUserTicketViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление/удаление категорий клиента.
        /// </summary>
        public static string ManagerUserToSection {
            get {
                return ResourceManager.GetString("ManagerUserToSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание склада.
        /// </summary>
        public static string ManagerWarehouseCreate {
            get {
                return ResourceManager.GetString("ManagerWarehouseCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование склада.
        /// </summary>
        public static string ManagerWarehouseEdit {
            get {
                return ResourceManager.GetString("ManagerWarehouseEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр складов.
        /// </summary>
        public static string ManagerWarehousesView {
            get {
                return ResourceManager.GetString("ManagerWarehousesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение профиля.
        /// </summary>
        public static string UserAccountEditTitle {
            get {
                return ResourceManager.GetString("UserAccountEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш кабинет.
        /// </summary>
        public static string UserDefaultTitle {
            get {
                return ResourceManager.GetString("UserDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция.
        /// </summary>
        public static string UserFAQ {
            get {
                return ResourceManager.GetString("UserFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание обращения.
        /// </summary>
        public static string UserFeedbackCreate {
            get {
                return ResourceManager.GetString("UserFeedbackCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список обращений.
        /// </summary>
        public static string UserFeedbacksView {
            get {
                return ResourceManager.GetString("UserFeedbacksView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр обращения.
        /// </summary>
        public static string UserFeedbackView {
            get {
                return ResourceManager.GetString("UserFeedbackView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание профиля.
        /// </summary>
        public static string UserProfileCreateTitle {
            get {
                return ResourceManager.GetString("UserProfileCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование профиля.
        /// </summary>
        public static string UserProfileEditTitle {
            get {
                return ResourceManager.GetString("UserProfileEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши профили.
        /// </summary>
        public static string UserProfilesViewTitle {
            get {
                return ResourceManager.GetString("UserProfilesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр профиля.
        /// </summary>
        public static string UserProfileViewTitle {
            get {
                return ResourceManager.GetString("UserProfileViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание заявки.
        /// </summary>
        public static string UserTicketCreateTitle {
            get {
                return ResourceManager.GetString("UserTicketCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование заявки.
        /// </summary>
        public static string UserTicketEditTitle {
            get {
                return ResourceManager.GetString("UserTicketEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши заявки.
        /// </summary>
        public static string UserTicketsViewTitle {
            get {
                return ResourceManager.GetString("UserTicketsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр заявки.
        /// </summary>
        public static string UserTicketViewTitle {
            get {
                return ResourceManager.GetString("UserTicketViewTitle", resourceCulture);
            }
        }
    }
}
