//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrintResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeliverySite.Resources.PrintResources", typeof(PrintResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Ни одна заявка не входит в выборку. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        /// 
        
        public static string PrintActRequisitesEmptyText
        {
            get
            {
                return ResourceManager.GetString("PrintAortEmptyText", resourceCulture);
            }
        }

        public static string PrintAortEmptyText {
            get {
                return ResourceManager.GetString("PrintAortEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Чеков нет. Ни одна заявка не входит в выборку. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintCheckEmptyText {
            get {
                return ResourceManager.GetString("PrintCheckEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Ни одна заявка не выбрана. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintListEmptyText {
            get {
                return ResourceManager.GetString("PrintListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Карта пуста. Ни одна заявка не входит в выборку. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintMapEmptyText {
            get {
                return ResourceManager.GetString("PrintMapEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Накладной нет. Ни одна заявка не выбрана. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintNaklEmptyText {
            get {
                return ResourceManager.GetString("PrintNaklEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Приложения нет. Ни одна заявка не выбрана. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintNaklPrilEmptyText {
            get {
                return ResourceManager.GetString("PrintNaklPrilEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Путевого нет. Ни одна заявка не входит в выборку. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintPutEmptyText {
            get {
                return ResourceManager.GetString("PrintPutEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Ни одна заявка не входит в выборку. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintRefundsEmptyText {
            get {
                return ResourceManager.GetString("PrintRefundsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Заявок нет. Ни одна заявка не входит в выборку. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintTicketsEmptyText {
            get {
                return ResourceManager.GetString("PrintTicketsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Наклеек нет. Ни одна заявка не входит в выборку. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintVinilEmptyText {
            get {
                return ResourceManager.GetString("PrintVinilEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Delivery.by&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;center style =&quot;font-family: sans-serif; margin-top: 30px; font-size: 16px;&quot;&gt;Заказ-поручений нет. Ни одна заявка не входит в выборку. Вернуться &lt;a href=&quot;#&quot; onclick=&quot;window.history.go(-1);return false;&quot;&gt;назад&lt;/a&gt;&lt;/center&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrintZPEmptyText {
            get {
                return ResourceManager.GetString("PrintZPEmptyText", resourceCulture);
            }
        }
    }
}
