//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TicketStatusesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicketStatusesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeliverySite.Resources.TicketStatusesResources", typeof(TicketStatusesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена (на складе).
        /// </summary>
        public static string Cancel_InStock {
            get {
                return ResourceManager.GetString("Cancel_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершена.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставлена.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дост. от кл. (у курьера).
        /// </summary>
        public static string DeliveryFromClient_InCourier {
            get {
                return ResourceManager.GetString("DeliveryFromClient_InCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дост. от кл. (на складе).
        /// </summary>
        public static string DeliveryFromClient_InStock {
            get {
                return ResourceManager.GetString("DeliveryFromClient_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмен (у курьера).
        /// </summary>
        public static string Exchange_InCourier {
            get {
                return ResourceManager.GetString("Exchange_InCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмен (на складе).
        /// </summary>
        public static string Exchange_InStock {
            get {
                return ResourceManager.GetString("Exchange_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На складе.
        /// </summary>
        public static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обработана.
        /// </summary>
        public static string NotProcessed {
            get {
                return ResourceManager.GetString("NotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В пути.
        /// </summary>
        public static string OnTheWay {
            get {
                return ResourceManager.GetString("OnTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработана.
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ (по адресу).
        /// </summary>
        public static string Refusal_ByAddress {
            get {
                return ResourceManager.GetString("Refusal_ByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ (в пути).
        /// </summary>
        public static string Refusal_OnTheWay {
            get {
                return ResourceManager.GetString("Refusal_OnTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ (у курьера).
        /// </summary>
        public static string Refusing_InCourier {
            get {
                return ResourceManager.GetString("Refusing_InCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат (на складе).
        /// </summary>
        public static string Return_InStock {
            get {
                return ResourceManager.GetString("Return_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенос (у курьера).
        /// </summary>
        public static string Transfer_InCourier {
            get {
                return ResourceManager.GetString("Transfer_InCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенос (на складе).
        /// </summary>
        public static string Transfer_InStock {
            get {
                return ResourceManager.GetString("Transfer_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К загрузке.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
    }
}
