//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Www123RouteGeocoder
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Result", Namespace = "http://schemas.datacontract.org/2004/07/SR.GeocodingAPI")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Delivery.Www123RouteGeocoder.Address[] AddressesField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthTokenField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorLevelField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Delivery.Www123RouteGeocoder.Address[] Addresses
        {
            get
            {
                return this.AddressesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AddressesField, value) != true))
                {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthToken
        {
            get
            {
                return this.AuthTokenField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuthTokenField, value) != true))
                {
                    this.AuthTokenField = value;
                    this.RaisePropertyChanged("AuthToken");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorLevel
        {
            get
            {
                return this.ErrorLevelField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorLevelField, value) != true))
                {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Address", Namespace = "http://schemas.datacontract.org/2004/07/SR.GeocodingAPI")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrectedField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeDegField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeDegField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Delivery.Www123RouteGeocoder.Property[] PropertiesField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Corrected
        {
            get
            {
                return this.CorrectedField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CorrectedField, value) != true))
                {
                    this.CorrectedField = value;
                    this.RaisePropertyChanged("Corrected");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Initial
        {
            get
            {
                return this.InitialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InitialField, value) != true))
                {
                    this.InitialField = value;
                    this.RaisePropertyChanged("Initial");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LatitudeDeg
        {
            get
            {
                return this.LatitudeDegField;
            }
            set
            {
                if ((this.LatitudeDegField.Equals(value) != true))
                {
                    this.LatitudeDegField = value;
                    this.RaisePropertyChanged("LatitudeDeg");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LongitudeDeg
        {
            get
            {
                return this.LongitudeDegField;
            }
            set
            {
                if ((this.LongitudeDegField.Equals(value) != true))
                {
                    this.LongitudeDegField = value;
                    this.RaisePropertyChanged("LongitudeDeg");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Delivery.Www123RouteGeocoder.Property[] Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true))
                {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Property", Namespace = "http://schemas.datacontract.org/2004/07/SR.GeocodingAPI")]
    [System.SerializableAttribute()]
    public partial class Property : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ValueField, value) != true))
                {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GeocodeOptions", Namespace = "http://schemas.datacontract.org/2004/07/SR.GeocodingAPI")]
    [System.SerializableAttribute()]
    public partial class GeocodeOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AddressesField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PropertiesField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Addresses
        {
            get
            {
                return this.AddressesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AddressesField, value) != true))
                {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true))
                {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:SmartRoutes/GeocodingAPI", ConfigurationName = "Www123RouteGeocoder.IAPI")]
    public interface IAPI
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:SmartRoutes/GeocodingAPI/IAPI/Login", ReplyAction = "urn:SmartRoutes/GeocodingAPI/IAPI/LoginResponse")]
        Delivery.Www123RouteGeocoder.Result Login(string userName, string password);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:SmartRoutes/GeocodingAPI/IAPI/Geocode", ReplyAction = "urn:SmartRoutes/GeocodingAPI/IAPI/GeocodeResponse")]
        Delivery.Www123RouteGeocoder.Result Geocode(Delivery.Www123RouteGeocoder.GeocodeOptions options, string authToken);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIChannel : Delivery.Www123RouteGeocoder.IAPI, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIClient : System.ServiceModel.ClientBase<Delivery.Www123RouteGeocoder.IAPI>, Delivery.Www123RouteGeocoder.IAPI
    {

        public APIClient()
        {
        }

        public APIClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public APIClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public APIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public APIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public Delivery.Www123RouteGeocoder.Result Login(string userName, string password)
        {
            return base.Channel.Login(userName, password);
        }

        public Delivery.Www123RouteGeocoder.Result Geocode(Delivery.Www123RouteGeocoder.GeocodeOptions options, string authToken)
        {
            return base.Channel.Geocode(options, authToken);
        }
    }
}
